monitor = , highres@highrr, 0x0, 1

exec-once = hyprpaper -c ~/dotfiles/hyprland/hyprpaper.conf
exec-once = hyprlock -c ~/dotfiles/hyprland/hyprlock.conf
exec-once = dunst &
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = udiskie &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/lib/kdeconnectd
exec-once = kdeconnect-indicator
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME

# programs
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$browser = librewolf

env = XCURSOR_SIZE, 24
env = XCURSOR_THEME,

env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = HYPRLAND_LOG_WLR=1
env = HYPRLAND_NO_RT=1
env = HYPRLAND_NO_SD_NOTIFY=1

env = GTK_THEME,
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

windowrule = suppressevent maximize,(.*)
windowrulev2 = fakefullscreen, class:(.*), title:(-Open Folder)
windowrule = float,title:(Open Folder)
windowrule = float,(protonvpn)
windowrule = float,(kitty)
windowrule = center, (.*)
windowrule = size 50% 80%, (kitty)
