group {
    insert_after_current = yes
    focus_removed_window = yes
    col.border_active = rgba(ffff0066)
    col.border_inactive = rgba(77770066)
    col.border_locked_active = rgba(ff550066)
    col.border_locked_inactive = rgba(77550066)

    groupbar {
	enabled = yes
	font_family = Sans
	font_size = 8
	gradients = yes
	height = 14
	# stacked = no
	priority = 3
	render_titles = yes
	scrolling = yes
	text_color = rgba(ffffffff)
	col.active = rgba(ffff0066)
	col.inactive = rgba(77770066)
	col.locked_active = rgba(ff550066)
	col.locked_inactive = rgba(77550066)
    }
}
