source = ~/dotfiles/hyprland/environment.conf
source = ~/dotfiles/hyprland/general.conf
source = ~/dotfiles/hyprland/input.conf
source = ~/dotfiles/hyprland/group.conf
source = ~/dotfiles/hyprland/misc.conf
source = ~/dotfiles/hyprland/keybinds.conf
