input {
    kb_layout = us
    kb_model =
    kb_variant =
    kb_options = 
    kb_rules = 
    kb_file =
    numlock_by_default = no
    resolve_binds_by_sym = no
    repeat_rate = 25
    repeat_delay = 600
    sensitivity = 0.0
    accel_profile = 
    force_no_accel = no
    left_handed = no
    scroll_points = 
    scroll_method = 2fg
    scroll_button = 0
    scroll_button_lock = no
    scroll_factor = 1.0
    natural_scroll = no
    follow_mouse = 1
    mouse_refocus = yes
    float_switch_override_focus = 1
    special_fallthrough = no
    off_window_axis_events = 1

    touchpad {
	disable_while_typing = yes
	natural_scroll = yes
	scroll_factor = 1.0
	middle_button_emulation = yes
	tap_button_map = 
	clickfinger_behavior = no
	tap-to-click = yes
	drag_lock = no
	tap-and-drag = yes
    }

    touchdevice {
	transform = 0
	output = [[Auto]]
	enabled = yes
    }

    tablet {
	transform = 0
	output =
	region_position = 0 0
	region_size = 0 0
	relative_input = no
	left_handed = no
	active_area_size = 0 0
	active_area_position = 0 0
    }
}
gestures {
    workspace_swipe = yes
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 300
    workspace_swipe_touch = no
    workspace_swipe_invert = yes
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = yes
    workspace_swipe_direction_lock = yes
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_forever = no
    workspace_swipe_use_r = no
}
