misc {
    disable_hyprland_logo = yes
    disable_splash_rendering = no
    col.splash = rgba(ffffffff)
    splash_font_family = Sans
    force_default_wallpaper = 0
    vfr = yes
    vrr = 0
    mouse_move_enables_dpms = no
    key_press_enables_dpms = no
    always_follow_on_dnd = yes
    layers_hog_keyboard_focus = yes
    animate_manual_resizes = yes
    animate_mouse_windowdragging = yes
    disable_autoreload = no
    enable_swallow = no
    swallow_regex = 
    swallow_exception_regex =
    focus_on_activate = yes
    no_direct_scanout = yes
    mouse_move_focuses_monitor = yes
    # suppress_portal_warnings = no
    render_ahead_of_time = no
    render_ahead_safezone = 1
    allow_session_lock_restore = no
    background_color = rgb(000000)
    close_special_on_empty = yes
    new_window_takes_over_fullscreen = 2 # 0
    # initial_workspace_tracking = 1
    # middle_click_paste = yes
}
binds {
    pass_mouse_when_bound = no
    scroll_event_delay = 300
    workspace_back_and_forth = no
    allow_workspace_cycles = no
    workspace_center_on = 0
    focus_preferred_method = 0
    ignore_group_lock = no
    movefocus_cycles_fullscreen = yes
    disable_keybind_grabbing = no
}
dwindle {
    pseudotile = yes
    force_split = 0
    preserve_split = yes
    smart_split = no
    smart_resizing = yes
    permanent_direction_override = no
    special_scale_factor = 1.0
    split_width_multiplier = 1.0
    no_gaps_when_only = 0
    use_active_for_splits = yes
    default_split_ratio = 1.0
}
opengl {
    nvidia_anti_flicker = yes
    force_introspection = 2
}
xwayland {
    use_nearest_neighbor = yes
    force_zero_scaling = no
}